DROP DATABASE IF EXISTS basedatos;

CREATE DATABASE basedatos;

USE basedatos;

CREATE TABLE jugador(
	ID INTEGER PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(60),
	CONTRASENYA VARCHAR(20)
)ENGINE=InnoDB;

CREATE TABLE partida(
	TABLERO VARCHAR(50),
	ID INTEGER PRIMARY KEY NOT NULL,
	GANADOR VARCHAR (60),
	FECHA VARCHAR(50),
	HORA VARCHAR(50),
	DURACION FLOAT
)ENGINE=InnoDB;


CREATE TABLE resultados(
	ID_J INTEGER NOT NULL,
	ID_P INTEGER NOT NULL,
	PUNTOS INTEGER,
	FOREIGN KEY (ID_J) REFERENCES jugador(ID),
	FOREIGN KEY (ID_P) REFERENCES partida(ID)
)ENGINE=InnoDB;


INSERT INTO jugador VALUES (1,'DAVID','UNO');
INSERT INTO jugador VALUES (2,'JUAN','DOS');
INSERT INTO jugador VALUES (3,'GERARD','TRES');
INSERT INTO jugador VALUES (4,'MIGUEL','QUATRO');

INSERT INTO partida VALUES ('Madrid',1,'Juan','12/03/2022','15:00',65.32);
INSERT INTO partida VALUES ('Barcelona',2,'David','22/12/2023','17:00',79.32);


INSERT INTO resultados VALUES(1,1,25);
INSERT INTO resultados VALUES(2,1,35);
